//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CofeWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasketItem
    {
        public int Id { get; set; }
        public int Amount { get; set; }
        public decimal TotalPrice { get; set; }
        public Nullable<int> Basket_Id { get; set; }
        public Nullable<int> Coffee_Id { get; set; }
    
        public virtual Basket Basket { get; set; }
        public virtual Coffee Coffee { get; set; }
    }
}
